name = "Flatom"
uuid = "4aa014a1-818e-4fc4-8cd2-74bff3621e60"
authors = ["Anton Oresten <antonoresten@gmail.com> and contributors"]
version = "0.1.0"

[deps]
BioStructures = "de9282ab-8554-53be-b2d6-f6c222edabfc"
PeriodicTable = "7b2266bf-644c-5ea3-82d8-af4bbd25a884"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StaticStrings = "4db0a0c5-418a-4e1d-8806-cb305fe13294"

[compat]
BioStructures = "4"
PeriodicTable = "1"
StaticArrays = "1"
StaticStrings = "0.2"
julia = "1.10"
