name = "Flatom"
uuid = "4aa014a1-818e-4fc4-8cd2-74bff3621e60"
authors = ["Anton Oresten <antonoresten@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
